version: '1.0'
stages:
  - clone
  - build   
  - bump-build-number
steps:
  clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: 'cgdevopsgcp/bump-build-number'
    revision: master
    git: github 
  BuildImage:
    title: Building Docker Image
    type: build
    image_name: cgcodefresh/bump-build-number 
    working_directory: "${{clone}}"
    dockerfile: "Dockerfile"
    tag: v6
  
  PushingToRegistry:
    type: push
    title: Pushing To Registry
    candidate: ${{BuildImage}}
    tags: [ "latest", "1.0.0" ]
    
  bump-build-number:
    title: Bump Build Version Number
    type: freestyle
    image: codefreshplugins/bump-build-number
    environment:
        - ANNOTATION_NAME=${{CF_BRANCH}}
    commands:
        - echo $CF_BUILD_ID
        - echo $CF_BUILD_NUMBER
  
